# Generated by Django 3.2.4 on 2021-06-28 14:54

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('plan', models.CharField(choices=[('startup', 'Startup'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='startup', max_length=12)),
                ('credits_bought', models.IntegerField(default=0)),
                ('plan_order_id', models.CharField(max_length=50)),
                ('credit_order_id', models.CharField(max_length=50)),
                ('last_plan_bought', models.DateTimeField(auto_now_add=True)),
                ('last_credits_bought', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('bought_on', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writer.user')),
            ],
        ),
    ]
