# Generated by Django 3.2.4 on 2021-07-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credits_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='credits_bought',
            field=models.IntegerField(default=3),
        ),
    ]
