# Generated by Django 3.2.4 on 2021-07-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0003_auto_20210704_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_credits_bought',
            new_name='last_credits_bought_on',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_plan_bought',
            new_name='last_plan_bought_on',
        ),
        migrations.AddField(
            model_name='user',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='credits_bought',
            field=models.IntegerField(default=5),
        ),
    ]
