# Generated by Django 3.2.4 on 2021-07-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0004_auto_20210705_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credits_bought',
            field=models.IntegerField(default=0),
        ),
    ]
