# Generated by Django 3.2.4 on 2021-07-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0006_alter_user_credits_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(default='stripe', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_url',
            field=models.CharField(default='regular', max_length=100),
        ),
    ]
